/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/models/Alien.gltf -o src/components/Alien.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Alien(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Alien.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions['Bite_Front'].reset().fadeIn(0.5).play()
    console.log(actions);
   return ()=>{
    actions['Dance'].fadeOut(0.5);
   }
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <group name="Alien_Blob">
            <skinnedMesh name="Cube144" geometry={nodes.Cube144.geometry} material={materials.Alien_Main} skeleton={nodes.Cube144.skeleton} />
            <skinnedMesh name="Cube144_1" geometry={nodes.Cube144_1.geometry} material={materials.Alien_Secondary} skeleton={nodes.Cube144_1.skeleton} />
          </group>
          <group name="Alien_Blob001">
            <skinnedMesh name="Cube000" geometry={nodes.Cube000.geometry} material={materials.Eye_Black} skeleton={nodes.Cube000.skeleton} />
            <skinnedMesh name="Cube000_1" geometry={nodes.Cube000_1.geometry} material={materials.Eye_White} skeleton={nodes.Cube000_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Alien.gltf')
